import pool from "../config/db.js";
import bcrypt from "bcryptjs";

// ============================================================
// User Model — raw SQL query methods
// ============================================================

export const User = {
  /**
   * Find user by email
   */
  async findByEmail(email) {
    const [rows] = await pool.execute(
      "SELECT * FROM users WHERE email = ? LIMIT 1",
      [email]
    );
    return rows[0] || null;
  },

  /**
   * Find user by ID (excludes password)
   */
  async findById(id) {
    const [rows] = await pool.execute(
      `SELECT id, name, email, profile_image, country, bio,
              travel_personality, followers_count, following_count,
              trips_count, countries_visited, is_verified, role, created_at
       FROM users WHERE id = ? LIMIT 1`,
      [id]
    );
    return rows[0] || null;
  },

  /**
   * Create a new user
   */
  async create({ name, email, password, country }) {
    const hashedPassword = await bcrypt.hash(password, 12);
    const [result] = await pool.execute(
      `INSERT INTO users (name, email, password, country)
       VALUES (?, ?, ?, ?)`,
      [name, email, hashedPassword, country || null]
    );

    // Fetch the created user (MySQL UUID is generated by DB)
    const [rows] = await pool.execute(
      "SELECT id, name, email, profile_image, country, bio, travel_personality, role, created_at FROM users WHERE email = ? LIMIT 1",
      [email]
    );
    return rows[0];
  },

  /**
   * Update user profile
   */
  async updateProfile(id, data) {
    const allowed = ["name", "country", "bio", "travel_personality", "profile_image"];
    const updates = [];
    const values = [];
    for (const key of allowed) {
      if (data[key] !== undefined) {
        updates.push(`${key} = ?`);
        values.push(data[key]);
      }
    }
    if (!updates.length) return this.findById(id);
    values.push(id);
    await pool.execute(`UPDATE users SET ${updates.join(", ")} WHERE id = ?`, values);
    return this.findById(id);
  },

  /**
   * Verify password
   */
  async verifyPassword(plainText, hashed) {
    return bcrypt.compare(plainText, hashed);
  },

  /**
   * Increment trip count
   */
  async incrementTripsCount(userId) {
    await pool.execute(
      "UPDATE users SET trips_count = trips_count + 1 WHERE id = ?",
      [userId]
    );
  },

  /**
   * Get user stats summary
   */
  async getStats(userId) {
    const [rows] = await pool.execute(
      `SELECT
         (SELECT COUNT(*) FROM trips WHERE user_id = ?) AS trips_count,
         (SELECT COUNT(*) FROM user_followers WHERE following_id = ?) AS followers_count,
         (SELECT COUNT(*) FROM user_followers WHERE follower_id = ?) AS following_count,
         (SELECT COUNT(*) FROM community_posts WHERE user_id = ?) AS posts_count`,
      [userId, userId, userId, userId]
    );
    return rows[0];
  },
};
